#!/bin/bash -l
#SBATCH --qos=normal
#SBATCH --partition=standard
#SBATCH --job-name RFAA
#SBATCH --mem=64G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --nodes=1
#SBATCH --output=/projects/ilfgrid/people/pqh443/Git_projects/RoseTTAFold-All-Atom/temp/logs/%j_out.txt
#SBATCH --error=/projects/ilfgrid/people/pqh443/Git_projects/RoseTTAFold-All-Atom/temp/logs/%j_err.txt

# Move to RF-AA directory and activate conda environment
cd /projects/ilfgrid/people/pqh443/Git_projects/RoseTTAFold-All-Atom

# Load miniconda and activate environment
module load miniconda
conda activate /projects/ilfgrid/apps/rosettafold_aa_kcd635/mamba_env

# Make sure GPU is not visible
export CUDA_VISIBLE_DEVICES=""

# Bin path
BIN_PATH=/projects/ilfgrid/apps/rosettafold_aa_kcd635/mamba_env/bin

CONFIG_PATHS=$1

# Read in config file from the list
full_path=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${CONFIG_PATHS}")
file=$(basename "$full_path")
config_name="${file%.*}"
echo "Running MSA prep using $full_path"

# Copy config to RF folder 
CONFIG=/projects/ilfgrid/people/pqh443/Git_projects/RoseTTAFold-All-Atom/rf2aa/config/inference/$file
cp $full_path $CONFIG

# Launch inference
$BIN_PATH/python -m rf2aa.run_inference --config-name $config_name
echo "Done MSA prep for $full_path"

# Remove config
rm $CONFIG

# Move log files
mv "/projects/ilfgrid/people/pqh443/Git_projects/RoseTTAFold-All-Atom/temp/logs/${SLURM_JOB_ID}_err.txt" "/projects/ilfgrid/people/pqh443/Git_projects/RoseTTAFold-All-Atom/temp/logs/${config_name}_MSA_err.txt"
mv "/projects/ilfgrid/people/pqh443/Git_projects/RoseTTAFold-All-Atom/temp/logs/${SLURM_JOB_ID}_out.txt" "/projects/ilfgrid/people/pqh443/Git_projects/RoseTTAFold-All-Atom/temp/logs/${config_name}_MSA_out.txt"
