defaults:
  - base
job_name: "7X9B_sm_no_templates"
output_path: "/projects/ilfgrid/people/pqh443/structural_benchmark/RFAA/7X9B_sm_no_templates"

loader_params:
  n_templ: 0

protein_inputs:
  A:
    fasta_file: /projects/ilfgrid/people/pqh443/structural_benchmark/fastas/receptors/7X9B_receptor.fasta

sm_inputs:
  B:
    input: /projects/ilfgrid/people/pqh443/structural_benchmark/sdfs/7X9B_ligand.sdf
    input_type: "sdf"
