 
defaults:
  - base
job_name: "ackr1_human___573"
output_path: "/projects/ilfgrid/people/pqh443/RF-AA_models/sm_inputs"

protein_inputs:
  A:
    fasta_file: /maps/projects/ilfgrid/data/RoseTTAFold-All-Atom/input/peptide_benchmark/fastas/ackr1_human.fasta

sm_inputs:
  B:
    input: /maps/projects/ilfgrid/data/RoseTTAFold-All-Atom/input/peptide_benchmark/SDFs/573.sdf
    input_type: "sdf"
